/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'home2': '&#xe909;',
            'house2': '&#xe909;',
            'connection': '&#xe91b;',
            'wifi': '&#xe91b;',
            'phone': '&#xe942;',
            'telephone': '&#xe942;',
            'phone-hang-up': '&#xe943;',
            'telephone2': '&#xe943;',
            'location': '&#xe947;',
            'map-marker': '&#xe947;',
            'location2': '&#xe948;',
            'map-marker2': '&#xe948;',
            'search': '&#xe986;',
            'magnifier': '&#xe986;',
            'volume-increase': '&#xea2b;',
            'volume6': '&#xea2b;',
            'volume-decrease': '&#xea2c;',
            'volume7': '&#xea2c;',
            'arrow-up2': '&#xea3a;',
            'up2': '&#xea3a;',
            'arrow-right2': '&#xea3c;',
            'right4': '&#xea3c;',
            'arrow-down2': '&#xea3e;',
            'down2': '&#xea3e;',
            'arrow-left2': '&#xea40;',
            'left4': '&#xea40;',
            'mic': '&#xe925;',
            'microphone': '&#xe925;',
            'books': '&#xe926;',
            'library': '&#xe926;',
            'cart': '&#xe93a;',
            'purchase': '&#xe93a;',
            'mobile': '&#xe958;',
            'cell-phone': '&#xe958;',
            'mobile2': '&#xe959;',
            'cell-phone2': '&#xe959;',
            'menu': '&#xe9bd;',
            'list3': '&#xe9bd;',
            'loop2': '&#xea2e;',
            'repeat2': '&#xea2e;',
            'circle-up': '&#xea41;',
            'up3': '&#xea41;',
            'circle-right': '&#xea42;',
            'right5': '&#xea42;',
            'circle-down': '&#xea43;',
            'down3': '&#xea43;',
            'circle-left': '&#xea44;',
            'left5': '&#xea44;',
            'home3': '&#xe902;',
            'house3': '&#xe902;',
            'pencil': '&#xe905;',
            'write': '&#xe905;',
            'quill': '&#xe907;',
            'feather': '&#xe907;',
            'image': '&#xe90d;',
            'picture': '&#xe90d;',
            'camera': '&#xe90f;',
            'photo': '&#xe90f;',
            'headphones': '&#xe910;',
            'headset': '&#xe910;',
            'play': '&#xe912;',
            'video': '&#xe912;',
            'mic': '&#xe927;',
            'microphone': '&#xe927;',
            'folder': '&#xe92f;',
            'directory': '&#xe92f;',
            'qrcode': '&#xe938;',
            'cart': '&#xe93b;',
            'purchase': '&#xe93b;',
            'coin-dollar': '&#xe93c;',
            'money': '&#xe93c;',
            'envelop': '&#xe945;',
            'mail': '&#xe945;',
            'location2': '&#xe949;',
            'map-marker2': '&#xe949;',
            'compass': '&#xe94a;',
            'direction': '&#xe94a;',
            'compass2': '&#xe94b;',
            'direction2': '&#xe94b;',
            'clock': '&#xe94e;',
            'time2': '&#xe94e;',
            'clock2': '&#xe94f;',
            'time3': '&#xe94f;',
            'tv': '&#xe95b;',
            'television': '&#xe95b;',
            'undo2': '&#xe967;',
            'left': '&#xe967;',
            'redo2': '&#xe968;',
            'right': '&#xe968;',
            'bubble': '&#xe96d;',
            'comment': '&#xe96d;',
            'user': '&#xe9d2;',
            'profile2': '&#xe9d2;',
            'users': '&#xe972;',
            'group': '&#xe972;',
            'user-plus': '&#xe973;',
            'user2': '&#xe973;',
            'cog': '&#xe994;',
            'gear': '&#xe994;',
            'bin': '&#xe9ac;',
            'trashcan': '&#xe9ac;',
            'airplane': '&#xe9af;',
            'travel': '&#xe9af;',
            'sphere': '&#xe9c9;',
            'globe': '&#xe9c9;',
            'earth': '&#xe9ca;',
            'globe2': '&#xe9ca;',
            'eye': '&#xe9ce;',
            'views': '&#xe9ce;',
            'eye-blocked': '&#xe9d1;',
            'views4': '&#xe9d1;',
            'bookmark': '&#xe9d3;',
            'ribbon': '&#xe9d3;',
            'star-empty': '&#xe9d7;',
            'rate': '&#xe9d7;',
            'star-full': '&#xe9d9;',
            'rate3': '&#xe9d9;',
            'heart': '&#xe9da;',
            'like': '&#xe9da;',
            'happy': '&#xe9df;',
            'emoticon': '&#xe9df;',
            'hipster': '&#xe9f9;',
            'emoticon27': '&#xe9f9;',
            'point-up': '&#xea03;',
            'finger': '&#xea03;',
            'notification': '&#xea08;',
            'warning2': '&#xea08;',
            'question': '&#xea09;',
            'help': '&#xea09;',
            'plus': '&#xea0a;',
            'add': '&#xea0a;',
            'minus': '&#xea0b;',
            'subtract': '&#xea0b;',
            'blocked': '&#xea0e;',
            'forbidden': '&#xea0e;',
            'cross': '&#xea0f;',
            'cancel': '&#xea0f;',
            'checkmark': '&#xea10;',
            'tick': '&#xea10;',
            'play2': '&#xea15;',
            'player': '&#xea15;',
            'pause': '&#xea16;',
            'player2': '&#xea16;',
            'stop': '&#xea17;',
            'player3': '&#xea17;',
            'previous': '&#xea18;',
            'player4': '&#xea18;',
            'next': '&#xea19;',
            'player5': '&#xea19;',
            'backward': '&#xea1a;',
            'player6': '&#xea1a;',
            'forward2': '&#xea1b;',
            'player7': '&#xea1b;',
            'play3': '&#xea1c;',
            'player8': '&#xea1c;',
            'pause2': '&#xea1d;',
            'player9': '&#xea1d;',
            'stop2': '&#xea1e;',
            'player10': '&#xea1e;',
            'backward2': '&#xea1f;',
            'player11': '&#xea1f;',
            'forward3': '&#xea20;',
            'player12': '&#xea20;',
            'volume-medium': '&#xea27;',
            'volume2': '&#xea27;',
            'volume-mute2': '&#xea2a;',
            'volume5': '&#xea2a;',
            'loop2': '&#xea2f;',
            'repeat2': '&#xea2f;',
            'arrow-up': '&#xea32;',
            'up': '&#xea32;',
            'arrow-right': '&#xea34;',
            'right3': '&#xea34;',
            'arrow-down': '&#xea36;',
            'down': '&#xea36;',
            'arrow-left': '&#xea38;',
            'left3': '&#xea38;',
            'arrow-up2': '&#xea3b;',
            'up2': '&#xea3b;',
            'arrow-right2': '&#xea3d;',
            'right4': '&#xea3d;',
            'arrow-down2': '&#xea3f;',
            'down2': '&#xea3f;',
            'arrow-left2': '&#xea45;',
            'left4': '&#xea45;',
            'circle-up': '&#xea46;',
            'up3': '&#xea46;',
            'circle-right': '&#xea47;',
            'right5': '&#xea47;',
            'circle-down': '&#xea48;',
            'down3': '&#xea48;',
            'circle-left': '&#xea49;',
            'left5': '&#xea49;',
            'checkbox-checked': '&#xea52;',
            'checkbox': '&#xea52;',
            'checkbox-unchecked': '&#xea53;',
            'checkbox2': '&#xea53;',
            'amazon': '&#xea87;',
            'brand': '&#xea87;',
            'google': '&#xea88;',
            'brand2': '&#xea88;',
            'google3': '&#xea8a;',
            'brand4': '&#xea8a;',
            'google-drive': '&#xea8f;',
            'brand9': '&#xea8f;',
            'facebook': '&#xea90;',
            'brand10': '&#xea90;',
            'facebook2': '&#xea91;',
            'brand11': '&#xea91;',
            'twitter': '&#xea96;',
            'brand16': '&#xea96;',
            'sina-weibo': '&#xea9a;',
            'brand20': '&#xea9a;',
            'feed2': '&#xea9b;',
            'rss': '&#xea9b;',
            'feed3': '&#xea9c;',
            'rss2': '&#xea9c;',
            'youtube': '&#xea9d;',
            'brand21': '&#xea9d;',
            'youtube2': '&#xea9e;',
            'brand22': '&#xea9e;',
            'steam': '&#xeaac;',
            'brand36': '&#xeaac;',
            'steam2': '&#xeaad;',
            'brand37': '&#xeaad;',
            'apple': '&#xeabe;',
            'brand53': '&#xeabe;',
            'android': '&#xeac0;',
            'brand55': '&#xeac0;',
            'windows8': '&#xeac2;',
            'brand57': '&#xeac2;',
            'skype': '&#xeac5;',
            'brand60': '&#xeac5;',
            'chrome': '&#xead9;',
            'browser': '&#xead9;',
            'edge': '&#xeadc;',
            'browser4': '&#xeadc;',
            'safari': '&#xeadd;',
            'browser5': '&#xeadd;',
            'html-five': '&#xeae4;',
            'w3c': '&#xeae4;',
            'html-five2': '&#xeae5;',
            'w3c2': '&#xeae5;',
            'home': '&#xe900;',
            'house': '&#xe900;',
            'pencil2': '&#xe906;',
            'write2': '&#xe906;',
            'music': '&#xe911;',
            'song': '&#xe911;',
            'spades': '&#xe917;',
            'cards': '&#xe917;',
            'clubs': '&#xe918;',
            'cards2': '&#xe918;',
            'diamonds': '&#xe919;',
            'cards3': '&#xe919;',
            'connection': '&#xe91c;',
            'wifi': '&#xe91c;',
            'phone': '&#xe944;',
            'telephone': '&#xe944;',
            'bubble': '&#xe96b;',
            'comment': '&#xe96b;',
            'bubbles': '&#xe96c;',
            'comments': '&#xe96c;',
            'bubbles3': '&#xe96f;',
            'comments3': '&#xe96f;',
            'bubbles4': '&#xe970;',
            'comments4': '&#xe970;',
            'user-tie': '&#xe976;',
            'user5': '&#xe976;',
            'quotes-left': '&#xe977;',
            'ldquo': '&#xe977;',
            'quotes-right': '&#xe978;',
            'rdquo': '&#xe978;',
            'spinner': '&#xe97a;',
            'loading2': '&#xe97a;',
            'spinner6': '&#xe97f;',
            'loading7': '&#xe97f;',
            'search': '&#xe987;',
            'magnifier': '&#xe987;',
            'key': '&#xe98d;',
            'password': '&#xe98d;',
            'lock': '&#xe98f;',
            'secure': '&#xe98f;',
            'unlocked': '&#xe990;',
            'lock-open': '&#xe990;',
            'cogs': '&#xe995;',
            'gears': '&#xe995;',
            'trophy': '&#xe99e;',
            'cup': '&#xe99e;',
            'gift': '&#xe99f;',
            'present': '&#xe99f;',
            'rocket': '&#xe9a5;',
            'jet': '&#xe9a5;',
            'fire': '&#xe9a9;',
            'flame': '&#xe9a9;',
            'lab': '&#xe9aa;',
            'beta': '&#xe9aa;',
            'bin': '&#xe9ad;',
            'trashcan': '&#xe9ad;',
            'bin2': '&#xe9ae;',
            'trashcan2': '&#xe9ae;',
            'switch': '&#xe9b6;',
            'clipboard': '&#xe9b8;',
            'board': '&#xe9b8;',
            'list-numbered': '&#xe9b9;',
            'options': '&#xe9b9;',
            'cloud-download': '&#xe9c2;',
            'cloud2': '&#xe9c2;',
            'cloud-upload': '&#xe9c3;',
            'cloud3': '&#xe9c3;',
            'link': '&#xe9cb;',
            'chain': '&#xe9cb;',
            'flag': '&#xe9cc;',
            'report': '&#xe9cc;',
            'attachment': '&#xe9cd;',
            'paperclip': '&#xe9cd;',
            'sun': '&#xe9d4;',
            'weather2': '&#xe9d4;',
            'contrast': '&#xe9d5;',
            'brightness-contrast': '&#xe9d6;',
            'star-half': '&#xe9d8;',
            'rate2': '&#xe9d8;',
            'heart-broken': '&#xe9db;',
            'heart2': '&#xe9db;',
            'warning': '&#xea07;',
            'sign': '&#xea07;',
            'blocked': '&#xea11;',
            'forbidden': '&#xea11;',
            'enter': '&#xea13;',
            'signin': '&#xea13;',
            'loop': '&#xea2d;',
            'repeat': '&#xea2d;',
            'loop2': '&#xea30;',
            'repeat2': '&#xea30;',
            'infinite': '&#xea31;',
            'shuffle': '&#xea33;',
            'random': '&#xea33;',
            'omega': '&#xea66;',
            'wysiwyg8': '&#xea66;',
            'sigma': '&#xea67;',
            'wysiwyg9': '&#xea67;',
            'mail2': '&#xea83;',
            'contact2': '&#xea83;',
            'mail5': '&#xea86;',
            'contact5': '&#xea86;',
            'amazon': '&#xea89;',
            'brand': '&#xea89;',
            'google': '&#xea8b;',
            'brand2': '&#xea8b;',
            'google2': '&#xea8d;',
            'brand3': '&#xea8d;',
            'google3': '&#xea8c;',
            'brand4': '&#xea8c;',
            'facebook': '&#xea93;',
            'brand10': '&#xea93;',
            'facebook2': '&#xea92;',
            'brand11': '&#xea92;',
            'instagram': '&#xea94;',
            'brand12': '&#xea94;',
            'telegram': '&#xea95;',
            'brand15': '&#xea95;',
            'twitter': '&#xea97;',
            'brand16': '&#xea97;',
            'sina-weibo': '&#xea9f;',
            'brand20': '&#xea9f;',
            'feed2': '&#xeaa0;',
            'rss': '&#xeaa0;',
            'feed3': '&#xeaa1;',
            'rss2': '&#xeaa1;',
            'youtube': '&#xeaa2;',
            'brand21': '&#xeaa2;',
            'youtube2': '&#xeaa3;',
            'brand22': '&#xeaa3;',
            'twitch': '&#xeaa4;',
            'brand23': '&#xeaa4;',
            'vimeo': '&#xeaa5;',
            'brand24': '&#xeaa5;',
            'steam': '&#xeaaf;',
            'brand36': '&#xeaaf;',
            'steam2': '&#xeaae;',
            'brand37': '&#xeaae;',
            'github': '&#xeab0;',
            'brand40': '&#xeab0;',
            'tux': '&#xeabd;',
            'brand52': '&#xeabd;',
            'apple': '&#xeac1;',
            'brand53': '&#xeac1;',
            'finder': '&#xeabf;',
            'brand54': '&#xeabf;',
            'android': '&#xeac3;',
            'brand55': '&#xeac3;',
            'windows': '&#xeac7;',
            'brand56': '&#xeac7;',
            'windows8': '&#xeac4;',
            'brand57': '&#xeac4;',
            'skype': '&#xeac6;',
            'brand60': '&#xeac6;',
            'paypal': '&#xead8;',
            'brand79': '&#xead8;',
            'chrome': '&#xeadb;',
            'browser': '&#xeadb;',
            'firefox': '&#xeada;',
            'browser2': '&#xeada;',
            'IE': '&#xeae0;',
            'browser3': '&#xeae0;',
            'edge': '&#xeadf;',
            'browser4': '&#xeadf;',
            'safari': '&#xeade;',
            'browser5': '&#xeade;',
            'opera': '&#xeae1;',
            'browser6': '&#xeae1;',
            'html-five': '&#xeae6;',
            'w3c': '&#xeae6;',
            'html-five2': '&#xeae7;',
            'w3c2': '&#xeae7;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/icon-/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
